apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - metallb-charts.yaml
  - hajimari-charts.yaml
  - codecentric-charts.yaml
  - longhorn-charts.yaml
  - external-dns-charts.yaml
  - traefik-charts.yaml
  - stakater-charts.yaml
  - deliveryhero-charts.yaml
  - weaveworks-kured-charts.yaml
  - prometheus-community-charts.yaml
  - node-feature-discovery-charts.yaml
  - minio-charts.yaml
